<a href="https://colab.research.google.com/github/officialaryansingh/pandas_learning/blob/main/pandas_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#****Pandas Library :****
-useful for Data Processing & Analysis

##Pandas Data Frame:
-pandas DataFrame is two-dimentional tabular data structure with labeled axes (rows and columns).

In [2]:
# importing the pandas library
import pandas as pd

Creating Padas DataFrame

In [3]:
# importing the house price data set

In [4]:
# defining the column names
df = pd.read_csv("/content/aug_train.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [6]:
df.iloc[0]

enrollee_id                                  8949
city                                     city_103
city_development_index                       0.92
gender                                       Male
relevent_experience       Has relevent experience
enrolled_university                 no_enrollment
education_level                          Graduate
major_discipline                             STEM
experience                                    >20
company_size                                  NaN
company_type                                  NaN
last_new_job                                    1
training_hours                                 36
target                                        1.0
Name: 0, dtype: object

In [7]:
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [8]:
print(df.columns)

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='object')

operating with the toy dataset

In [9]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# 1. Load data
df = pd.read_csv("/content/aug_train.csv")

# 2. Simple Preprocessing: Drop non-numeric columns for now
# (In a real project, you would encode these instead of dropping them!)
numeric_df = df.select_dtypes(include=['number'])

# 3. Define X and y
# Ensure the target is NOT in X
x = numeric_df.drop(["enrollee_id", "city_development_index"], axis=1)
y = numeric_df["city_development_index"]

# 4. Split with correct parameter name: random_state
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# 5. Train and Evaluate
model = LinearRegression()
model.fit(x_train, y_train)

print("Score:", model.score(x_test, y_test))

Score: 0.11333970478025523

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df = pd.read_csv("/content/aug_train.csv")

In [13]:
df.iloc[0]

enrollee_id                                  8949
city                                     city_103
city_development_index                       0.92
gender                                       Male
relevent_experience       Has relevent experience
enrolled_university                 no_enrollment
education_level                          Graduate
major_discipline                             STEM
experience                                    >20
company_size                                  NaN
company_type                                  NaN
last_new_job                                    1
training_hours                                 36
target                                        1.0
Name: 0, dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [15]:
print(df.columns)

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'target'],
      dtype='object')

In [16]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [17]:
from sklearn.datasets import fetch_california_housing

KeyboardInterrupt:

In [ ]:
house_dataset = fetch_california_housing()

In [ ]:
type(house_dataset)

In [ ]:
print(house_dataset)

In [ ]:
# pandas DataFrame
calafornia_df = pd.DataFrame(house_dataset.data,columns = house_dataset.feature_names)

In [ ]:
calafornia_df.head()

In [ ]:
calafornia_df.shape

Importing the data from a CSV file to a pandas DataFrame

In [ ]:
# csv file to pandas df
house_df = pd.read_csv("/content/housing.csv")
housing_dataset = house_df
house_df.iloc[0]
house_df.info()
print(housing_dataset.columns)

In [ ]:
type(housing_dataset)

In [ ]:
type(calafornia_df)

In [ ]:
housing_dataset.head()

##to assign the columns name in pd data frame we use:

calafornia_df = pd.DataFrame(house_dataset.data,columns = house_dataset.feature_names)

In [ ]:
ho_df = pd.DataFrame(house_dataset.data,columns = house_dataset.feature_names)

In [ ]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

# Load the housing.csv file with appropriate delimiter and no header
housing_df_direct = pd.read_csv('/content/housing.csv', sep=r'\s+', header=None, names=column_names)
display(housing_df_direct.head())

In [ ]:
display(housing_df_direct.info())

In [ ]:
ho_df.head()

ho_df.info()

Loading the data from the excel file with pandas DataFram:

pd.read_excel("file.path")

Exporting a data to a csv file

In [ ]:
# this is how you can convert Datafram to a csv file
calafornia_df.to_csv("calafornia.csv")

##**** exporting all the file from a padas DataFrame and importing it to the excel file****  :

df.to_excel('filename')

In [ ]:
# creating a DataFrame with random values
import numpy as np

random_df = pd.DataFrame(np.random.rand(20,10))

In [ ]:
random_df.head()

In [ ]:
#  Finding the no. of rows and columns
random_df.shape

##Inspecting a DataFrame

In [ ]:
# First 5 rows in a DataFrame
calafornia_df.head()

In [ ]:
# Last 5 rows in a DataFrame
calafornia_df.tail()

In [ ]:
# information about the DataFrame
calafornia_df.info()

In [ ]:
# finding the no. of missing values : df.isnull.sum()
calafornia_df.isnull().sum()

In [ ]:
# housing DataFrame
housing_df_direct.head()

In [ ]:
# counting RAD based on the labels:
housing_df_direct.value_counts('RAD')

In [ ]:
# group the values based on the maen

# housing_df_direct.groupby('RAD').mean()
housing_df_direct.groupby('MEDV').mean()